import React, { useState, useEffect, useRef } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpLeft, ArrowLeft, ArrowRight, ArrowDownUp, ArrowDown, Check, CheckCheck, ShieldCheck, Clock3, Headphones, Search, Home as HomeIcon, X, Copy, ChevronDown, ChevronLeft, CircleHelp, Wallet, Plus, Settings, LogOut, LayoutDashboard, ReceiptText, Layers, Percent, Network, Banknote, LoaderCircle, Upload, CheckCircle2, Info, Download, Menu, ExternalLink, RefreshCw, LockKeyhole } from 'lucide-react';
import { calculate } from '../server/calculation.js';
import QRCode from 'qrcode';
import '@fontsource/ibm-plex-sans-arabic/400.css';
import '@fontsource/ibm-plex-sans-arabic/500.css';
import '@fontsource/ibm-plex-sans-arabic/600.css';
import '@fontsource/ibm-plex-sans-arabic/700.css';
import './styles.css';

const money = n => new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(n || 0);
const unit = c => ({USD:'دولار',SYP:'ليرة سورية',USDT:'USDT'}[c] || c);
const commissionLabel = order => order.service_id === 'exchange' || order.commission_type === 'none' ? 'بدون عمولة' : `${money(order.commission)} ${unit(order.currency)} (${order.commission_type === 'fixed' ? 'عمولة ثابتة' : order.commission_percent+'٪'})`;
const directionName = d => ({sell:'بيع USDT',buy:'شراء USDT','usd-syp':'بيع الدولار','syp-usd':'شراء الدولار'}[d]);
const statuses = ['بانتظار الدفع','تم إرسال إثبات الدفع','قيد المراجعة','تم تأكيد الدفع','قيد التنفيذ','مكتملة','مرفوضة','ملغاة'];
async function api(url,options={}) { const response = await fetch('/api'+url,{...options,headers:options.body instanceof FormData ? {} : {'Content-Type':'application/json'},body:options.body && !(options.body instanceof FormData) ? JSON.stringify(options.body) : options.body}); const raw=await response.text();let data={};try{data=raw?JSON.parse(raw):{};}catch{const e=new Error(response.ok?'استجابة غير صالحة من الخادم. يرجى المحاولة مجددًا.':'تعذر تنفيذ العملية على الخادم.');e.status=response.status;e.responseText=raw;throw e;}if(!response.ok){const e=new Error(data.error || 'تعذر تنفيذ العملية.');e.status=response.status;throw e;}return data; }
function Icon({children,className=''}){return <span className={'icon-box '+className}>{children}</span>}
function Mark(){return <svg viewBox="0 0 110 76" fill="none" aria-hidden="true"><path d="M9 51V10h10l26 30 25-30h14c28 0 29 31 10 38l15 20H93L71 38h12c12 0 12-15 0-15h-7L46 58 22 31v20z" fill="currentColor"/><path d="M5 63c24 16 51-1 74-25l-13 3 7-9 20-4-7 21-4-9C59 72 29 80 5 63Z" fill="#c5a15b"/></svg>}
function Brand({settings,small=false}){return <a href="/" className={'brand '+(small?'brand-small':'')} aria-label="المارديني، الرئيسية"><img src="/mardini-logo.png" alt={settings?.name || 'المارديني'}/></a>}
function Button({children,variant='',className='',busy=false,...props}){return <button className={'button '+variant+' '+className} disabled={busy||props.disabled} {...props}>{busy?<LoaderCircle className="spin" size={18}/>:null}{children}</button>}
function Field({label,children,hint}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
function Notice({children,error=false}){return <div className={'notice '+(error?'error':'')} role={error?'alert':undefined}><Info size={18}/><span>{children}</span></div>}
function PaymentQr({value}){const [src,setSrc]=useState('');useEffect(()=>{let live=true;if(value)QRCode.toDataURL(String(value),{width:220,margin:2,errorCorrectionLevel:'M'}).then(x=>live&&setSrc(x)).catch(()=>setSrc(''));return()=>{live=false};},[value]);return src?<img className="payment-qr" src={src} alt="رمز QR للدفع"/>:null}
function Status({value}){return <span className={'status '+(value==='مكتملة'?'done':['مرفوضة','ملغاة'].includes(value)?'failed':'')}><i/>{value}</span>}
function App(){
 const [config,setConfig]=useState(null),[error,setError]=useState(''),[path,setPath]=useState(location.pathname),[install,setInstall]=useState(null),[toast,setToast]=useState('');
 const go=(to)=>{history.pushState({},'',to);setPath(to.split('?')[0]);window.scrollTo({top:0,behavior:'instant'});};
 useEffect(()=>{const pop=()=>setPath(location.pathname);const click=e=>{const a=e.target.closest('a');if(a&&a.origin===location.origin&&!a.download&&!a.target&&!e.metaKey&&!e.ctrlKey){e.preventDefault();go(a.pathname+a.search);}};window.addEventListener('popstate',pop);document.addEventListener('click',click);api('/config').then(setConfig).catch(()=>setError('تعذر الاتصال بالخدمة. يرجى إعادة المحاولة.'));const prompt=e=>{e.preventDefault();setInstall(e);};window.addEventListener('beforeinstallprompt',prompt);return()=>{window.removeEventListener('popstate',pop);document.removeEventListener('click',click);window.removeEventListener('beforeinstallprompt',prompt);};},[]);
 const notify=message=>{setToast(message);setTimeout(()=>setToast(''),3500);};
 if(!config)return <div className="loading-screen"><Brand/><div>{error?<><Notice error>{error}</Notice><Button onClick={()=>location.reload()}>إعادة المحاولة</Button></>:<LoaderCircle className="spin"/>}</div></div>;
 if(path.startsWith('/admin'))return <Admin config={config} refresh={()=>api('/config').then(setConfig)} notify={notify}/>;
 const isHome=path==='/',isTrack=path==='/track'||path.startsWith('/order/');
 return <><header className="site-header"><div className="header-inner"><Brand settings={config.settings}/><nav className="desktop-nav"><a className={isHome?'active':''} href="/">الرئيسية</a><a className={path==='/usdt'||path==='/exchange'?'active':''} href="/#services" onClick={e=>{e.preventDefault();go('/');setTimeout(()=>document.getElementById('services')?.scrollIntoView({behavior:'smooth'}),80);}}>خدماتنا</a><a className={path==='/help'?'active':''} href="/help">المساعدة والدعم</a></nav><a href="/track" className="header-track"><Search size={17}/>تتبع طلب<ArrowUpLeft size={16}/></a></div></header>
 {config.settings.announcement&&<div className="announcement">{config.settings.announcement}</div>}
 {!config.settings.active&&<div className="container"><Notice error>المنصة متوقفة مؤقتًا. يمكنك متابعة طلباتك السابقة.</Notice></div>}
 <main>{isHome?<Home config={config} go={go}/>:path==='/usdt'||path==='/exchange'?<Service key={path} type={path.slice(1)} config={config} go={go}/>:path==='/track'?<Track go={go}/>:path.startsWith('/order/')?<Order id={decodeURIComponent(path.split('/')[2])} config={config} notify={notify} go={go}/>:path==='/help'?<Help settings={config.settings}/>:<div className="page narrow"><h1>الصفحة غير موجودة</h1><a href="/">العودة للرئيسية</a></div>}</main>
 <footer className="site-footer container"><Brand settings={config.settings} small/><p>خطوتك الأسهل لحوالاتك المالية.</p><span>© {new Date().getFullYear()} {config.settings.name}. جميع الحقوق محفوظة.</span><a href="/help">تواصل معنا<ArrowUpLeft size={14}/></a></footer>
 {install&&<button className="install-button" onClick={async()=>{await install.prompt();setInstall(null);}}><Download size={16}/>إضافة إلى الشاشة الرئيسية</button>}
 <nav className="mobile-nav"><a href="/" className={isHome?'active':''}><HomeIcon size={21}/>الرئيسية</a><a href="/track" className={isTrack?'active':''}><Search size={21}/>تتبع طلب</a><a href="/help" className={path==='/help'?'active':''}><Headphones size={21}/>المساعدة</a></nav>
 {toast&&<div className="toast" role="status"><CheckCircle2 size={19}/>{toast}</div>}</>;
}
function Home({config,go}){
 let example = '—';
 try { example = new Intl.NumberFormat('en-US', {minimumFractionDigits:2, maximumFractionDigits:6}).format(calculate({service:'usdt',direction:'sell',balance:'USD',amount:100},config).finalAmount); } catch {}
 return <div className="home container"><section className="hero"><div className="hero-content"><div className="eyebrow"><span className="live-dot"/>حوالات أقرب. حياة أسهل.</div><h1>حوالاتك المالية<br/><span>ببساطة</span><span className="gold-dot">.</span></h1><p className="hero-description">شراء وبيع <bdi>USDT</bdi> وتصريف أرصدة شام كاش<br className="desktop-break"/> بسهولة وسرعة. كل ما تحتاجه، في مكان واحد.</p><div className="hero-actions"><Button onClick={()=>document.getElementById('services').scrollIntoView({behavior:'smooth'})}>ابدأ معاملتك الآن<ArrowLeft size={19}/></Button><span className="no-account"><ShieldCheck size={17}/>بدون إنشاء حساب</span></div><div className="hero-trust"><span><Check size={14}/>عمولات واضحة</span><span><Check size={14}/>تأكيد يدوي وآمن</span><span><Check size={14}/>دعم يهتم بك</span></div></div>
  <div className="hero-visual" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="visual-dot dot-one"/><div className="visual-dot dot-two"/><div className="floating-security"><span><ShieldCheck size={20}/></span><div>بكل راحة واطمئنان<small>خطوات واضحة، من البداية للنهاية</small></div></div><div className="transfer-card"><div className="transfer-card-top"><div className="mini-brand"><img src="/mardini-logo.png" alt=""/>المارديني</div><span className="demo-label">مثال توضيحي</span></div><div className="transfer-row"><span className="currency-symbol tether">₮</span><div><small>أنت ترسل</small><strong><bdi>100.00 <span>USDT</span></bdi></strong></div><span className="network-pill">TRC20</span></div><div className="transfer-divider"><span/><div><ArrowDown size={17}/></div><span/></div><div className="transfer-row"><span className="currency-symbol sham"><Wallet size={26}/></span><div><small>تستلم في شام كاش</small><strong><bdi>{example}</bdi> <span>دولار</span></strong></div><CheckCircle2 className="received-check" size={21}/></div><div className="transfer-bottom"><span><span className="live-dot"/>واضحة من أول خطوة</span><ShieldCheck size={16}/></div></div><div className="floating-speed"><Icon><Clock3 size={20}/></Icon><div><strong>وقتك يهمنا</strong><small>تجربة بسيطة. خطوات أقل.</small></div><span className="tiny-spark">✦</span></div><div className="visual-caption"><span/>أموالك تتحرك، وأنت مرتاح<span/></div></div></section>
 <section id="services" className="services-section"><div className="section-heading"><div><span className="section-kicker">خدماتنا</span><h2>ماذا تريد أن تفعل اليوم؟</h2></div><p>اختر خدمتك، ودع الباقي علينا.</p></div><div className="service-cards">{config.services.map((s,i)=><article className={'service-card '+(i===0?'usdt-card':'exchange-card')} key={s.id}><div className="service-card-heading"><Icon className={i===0?'teal':'gold'}><img className="service-icon-image" src={'/api/service-icon/'+s.id} alt={s.name} onError={e=>{e.currentTarget.style.display='none';e.currentTarget.nextElementSibling.style.display='grid';}}/><span className="service-icon-fallback" style={{display:'none'}}>{i===0?'₮':'↕'}</span></Icon><span className={'service-badge '+(!s.active?'muted':'')}>{!s.active?'متوقفة مؤقتًا':i===0?'بيع وشراء':'بدون عمولة'}</span></div><h3>{s.name}</h3><p>{s.description}</p><div className="service-meta">{i===0?<><span>USDT</span><ArrowDownUp size={13}/><span>شام كاش</span></>:<><span>دولار</span><ArrowDownUp size={13}/><span>ليرة سورية</span></>}</div><a href={'/'+s.id} className={'service-button '+(i===0?'filled':'')}>{i===0?'بدء العملية':'بدء التصريف'}<ArrowLeft size={18}/></a></article>)}</div></section>
 <section className="how-section"><div className="section-heading"><div><span className="section-kicker">ببساطة، هكذا تتم</span><h2>ثلاث خطوات. واطمئن على حوالتك.</h2></div><span className="subtle-caption">من البداية للنهاية، أنت على اطلاع.</span></div><div className="steps"><div className="step"><span className="step-number">01</span><div><h3>اختر وأدخل المبلغ</h3><p>حدد خدمتك واعرف المبلغ الذي ستستلمه فورًا.</p></div></div><span className="step-connector"/><div className="step"><span className="step-number">02</span><div><h3>حوّل وأرفق الإثبات</h3><p>اتبع تعليمات الدفع وأرسل إثبات التحويل.</p></div></div><span className="step-connector"/><div className="step"><span className="step-number">03</span><div><h3>تابع طلبك بسهولة</h3><p>احتفظ برقم طلبك وتابع حالته في أي وقت.</p></div></div></div></section>
 <section className="support-strip"><div className="support-start"><Icon><Headphones size={25}/></Icon><div><h3>هل تحتاج إلى مساعدة؟</h3><p>نحن هنا لنجعل تجربتك أسهل، خطوة بخطوة.</p><p className="company-location">موقع الشركة: حلب الجديدة / شارع ارينا مول / جانب مرطبات ياسمين الشام</p></div></div><a href="/help">تواصل مع الدعم<ArrowUpLeft size={18}/></a></section><div className="bottom-assurance"><LockKeyhole size={14}/><span>بياناتك بأمان. معاملات واضحة، بدون تعقيد.</span></div></div>
}
function UsdtCoin({small=false}){return <span className={'usdt-coin '+(small?'small':'')} aria-hidden="true"><span>₮</span></span>}
function PageHeading({title,subtitle,usdt=false}){return <><a className="back-link" href="/"><ArrowRight size={17}/>العودة للرئيسية</a><div className={'page-heading '+(usdt?'page-heading-usdt':'')}>{usdt&&<div className="usdt-hero-coins" aria-hidden="true"><UsdtCoin/><UsdtCoin small/></div>}<div><span className="section-kicker">المارديني، معك بكل خطوة</span><h1>{title}</h1><p>{subtitle}</p></div></div></>}
function Service({type,config,go}){
 const service=config.services.find(s=>s.id===type),isUsdt=type==='usdt';
 const [direction,setDirection]=useState(service.directions[0]||(isUsdt?'sell':'usd-syp')),[amount,setAmount]=useState(''),[balance,setBalance]=useState(service.currencies[0]||'USD'),[network,setNetwork]=useState(config.networks[0]?.id||''),[recipient,setRecipient]=useState(''),[proofFile,setProofFile]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const input={service:type,direction,amount,balance,network,recipient};let quote=null,quoteError='';if(amount){try{quote=calculate(input,config);}catch(e){quoteError=e.message;}}
 const currency=isUsdt?(direction==='sell'?'USDT':balance):(direction==='usd-syp'?'USD':'SYP');
 const selectedNetwork=config.networks.find(n=>String(n.id)===String(network));
 const payCurrency=isUsdt?(direction==='sell'?'USDT':balance):currency;
 const payAddress=payCurrency==='USDT'?selectedNetwork?.address:config.wallets?.[payCurrency];
 const payOwner=payCurrency==='USDT'?'':config.walletOwners?.[payCurrency];
 const showQr=payCurrency==='USDT'?selectedNetwork?.qr_enabled!==false:config.walletQr?.[payCurrency]!==false;
 async function copy(value){try{await navigator.clipboard.writeText(value);}catch{}}
 async function submit(e){e.preventDefault();setError('');if(!proofFile){setError('يرجى إرفاق صورة إيصال التحويل أولًا.');return;}setBusy(true);try{const order=await api('/orders',{method:'POST',body:input});const data=new FormData();data.append('proof',proofFile);await api('/orders-proof/'+order.id,{method:'POST',body:data});go('/order/'+order.id+'?new=1');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="page narrow service-page"><PageHeading title={service.name} subtitle={isUsdt?'بيع أو شراء USDT بخطوات واضحة في صفحة واحدة.':'حوّل بين الدولار والليرة السورية بسهولة ووضوح.'} usdt={isUsdt}/>{!service.active||!config.settings.active?<Notice error>هذه الخدمة متوقفة مؤقتًا. يرجى العودة لاحقًا.</Notice>:<form className="form-card smart-service-card" onSubmit={submit} noValidate>
  <div className="segmented service-switch">{service.directions.map(d=><button type="button" className={direction===d?'selected':''} key={d} onClick={()=>{setDirection(d);setError('');setRecipient('');}}>{directionName(d)}</button>)}</div>
  {isUsdt&&<div className="service-section"><div className="service-section-head"><span>١</span><div><strong>أين ستحوّل؟</strong><small>اختر الشبكة ثم انسخ عنوان الدفع.</small></div></div><Field label="شبكة التحويل"><select value={network} onChange={e=>setNetwork(e.target.value)}><option value="" disabled>اختر الشبكة</option>{config.networks.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></Field>{!config.networks.length?<Notice>لا توجد شبكات مفعلة حاليًا. يرجى التواصل مع الدعم.</Notice>:direction==='sell'&&<PaymentDestination address={payAddress} owner={payOwner} qr={showQr} label={selectedNetwork?'عنوان USDT · '+selectedNetwork.name:'عنوان USDT'} copy={copy}/>}</div>}
  {!isUsdt&&<div className="service-section"><div className="service-section-head"><span>١</span><div><strong>حوّل إلى حسابنا</strong><small>أرسل من حساب شام كاش الذي تريد استلام التصريف عليه.</small></div></div><PaymentDestination address={payAddress} owner={payOwner} qr={showQr} label={'حساب شام كاش · '+unit(payCurrency)} copy={copy}/></div>}
  {isUsdt&&direction==='buy'&&<div className="service-section compact-payment"><PaymentDestination address={payAddress} owner={payOwner} qr={showQr} label={'حساب شام كاش · '+unit(payCurrency)} copy={copy}/></div>}
  <div className="service-section"><div className="service-section-head"><span>{isUsdt?'٢':'٢'}</span><div><strong>المبلغ والاستلام</strong><small>سترى الناتج والرسوم مباشرة أثناء الكتابة.</small></div></div>
   <div className="money-row amount-only"><Field label={isUsdt?(direction==='sell'?'المبلغ المُرسل USDT':`المبلغ المُرسل ${unit(currency)}`):`المبلغ المُرسل ${unit(currency)}`}><div className="amount-input compact-amount"><input aria-label="المبلغ" inputMode="decimal" placeholder="0.00" value={amount} onChange={e=>setAmount(e.target.value)} dir="ltr"/><span>{unit(currency)}</span></div></Field></div>
   {isUsdt&&<div className="recipient-currency-row"><Field label={direction==='buy'?'عنوان USDT الذي تريد الاستلام عليه':'حساب شام كاش المستفيد'}><input dir="ltr" value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder={direction==='buy'?'عنوان محفظتك':'رقم حساب شام كاش'}/></Field><Field label={direction==='sell'?'العملة':'عملة الدفع'}><select value={balance} onChange={e=>setBalance(e.target.value)}>{service.currencies.map(c=><option value={c} key={c}>{c==='SYP'?'SYP':c==='USD'?'USD':c}</option>)}</select></Field></div>}
   {!isUsdt&&<div className="exchange-result" aria-live="polite"><span>مبلغ الاستلام</span><strong>{money(quote?.finalAmount)} <small>{unit(quote?.finalCurrency||(direction==='usd-syp'?'SYP':'USD'))}</small></strong><em>1 دولار = {money(quote?.rate||(direction==='usd-syp'?config.rates?.sellUsd:config.rates?.buyUsd))} ليرة سورية</em></div>}
  </div>
  {isUsdt&&<div className="compact-summary" aria-live="polite"><div><span>المبلغ المُرسل</span><strong>{money(quote?.amount)} {unit(currency)}</strong></div><div><span>{direction==='sell'?'العمولة':'رسوم الشبكة'}</span><strong>{money(direction==='sell'?quote?.commission:quote?.networkFee)} دولار</strong></div><div className="summary-result"><span>مبلغ الاستلام</span><strong>{money(quote?.finalAmount)} {unit(quote?.finalCurrency||(direction==='sell'?balance:'USDT'))}</strong></div></div>}
  {!isUsdt&&<div className="important-note"><Info size={20}/><div><strong>مهم قبل التحويل</strong><p>سيتم تحويل المبلغ إلى نفس حساب شام كاش الذي أرسلت منه. لا تُخفِ اسم المرسل أثناء التحويل.</p></div></div>}
  <div className="service-section proof-preview"><div className="service-section-head"><span>٣</span><div><strong>إثبات التحويل</strong><small>أرفق صورة الإيصال قبل تأكيد الطلب.</small></div></div><label className="upload-area service-proof-upload"><Upload size={22}/><strong>{proofFile?proofFile.name:'اضغط لاختيار صورة إيصال التحويل'}</strong><small>{proofFile?'تم اختيار الصورة · اضغط لتغييرها':'PNG أو JPG أو WEBP · حتى 5 ميغابايت'}</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>5*1024*1024){setProofFile(null);setError('حجم الصورة يجب ألا يتجاوز 5 ميغابايت.');e.target.value='';return;}setProofFile(file);setError('');}}/></label></div>
  {quoteError&&<Notice error>{quoteError}</Notice>}{error&&<Notice error>{error}</Notice>}<Button className="full primary-submit" busy={busy} disabled={!quote||!proofFile||(isUsdt&&!recipient)||(isUsdt&&!network)} type="submit">تأكيد ومتابعة الدفع<ArrowLeft size={18}/></Button><p className="form-footnote"><LockKeyhole size={13}/>ستراجع تفاصيل الدفع والإيصال قبل إرسال الطلب للإدارة.</p>
 </form>}<MiniSupport/></div>
}
function PaymentDestination({address,owner,qr,label,copy}){return <div className="inline-payment">{qr&&address&&<PaymentQr value={address}/>}<div className="inline-payment-info"><small>{label}</small>{address?<><div className="payment-address-line"><bdi>{address}</bdi><button type="button" className="icon-copy" onClick={()=>copy(address)} aria-label="نسخ العنوان" title="نسخ"><Copy size={17}/></button></div>{owner&&<strong>{owner}</strong>}</>:<span className="payment-missing">لم تتم إضافة بيانات الدفع بعد.</span>}</div></div>}
function MiniSupport(){return <a href="/help" className="mini-support"><Headphones size={18}/>هل تحتاج إلى مساعدة؟<span>تواصل معنا</span><ArrowUpLeft size={15}/></a>}
function Track({go}){const [id,setId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);async function track(e){e.preventDefault();setError('');setBusy(true);try{const order=await api('/orders/'+encodeURIComponent(id.trim().replace(/^#/,'')));go('/order/'+order.id);}catch(e){setError(e.message);}finally{setBusy(false);}}return <div className="page narrow"><PageHeading title="تتبع طلب" subtitle="حوالتك، خطوة بخطوة. أدخل رقم طلبك للاطلاع على آخر تحديث."/><form className="form-card track-card" onSubmit={track} noValidate><Icon className="teal"><Search size={28}/></Icon><h2>أين وصلت حوالتك؟</h2><p>ستجد رقم الطلب في صفحة تأكيد العملية.</p><Field label="رقم الطلب"><input dir="ltr" placeholder="#MRD-…" value={id} onChange={e=>setId(e.target.value)} autoComplete="off"/></Field>{error&&<Notice error>{error}</Notice>}<Button className="full" busy={busy} disabled={!id.trim()}>تتبع الطلب<ArrowLeft size={17}/></Button></form><MiniSupport/></div>}
function Order({id,config,notify,go}){
 const [order,setOrder]=useState(null),[error,setError]=useState(''),[txid,setTxid]=useState(''),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[success,setSuccess]=useState(new URLSearchParams(location.search).has('new'));
 const load=()=>api('/orders/'+encodeURIComponent(id)).then(setOrder).catch(e=>setError(e.message));useEffect(()=>{load();},[id]);
 async function copy(value){try{await navigator.clipboard.writeText(value);notify('تم النسخ بنجاح');}catch{notify('تعذر النسخ. يمكنك تحديد النص ونسخه يدويًا.');}}
 async function send(e){e.preventDefault();setBusy(true);setError('');try{const data=new FormData();data.append('txid',txid);if(file)data.append('proof',file);await api('/orders/'+id+'/proof',{method:'POST',body:data});await load();notify('تم إرسال إثبات الدفع بنجاح');}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!order)return <div className="page narrow">{error?<Notice error>{error}</Notice>:<LoaderCircle className="spin"/>}</div>;
 const showPaymentQr=order.currency==='USDT'?config.networks.find(n=>n.name===order.network)?.qr_enabled!==false:config.walletQr?.[order.currency]!==false;
  return <div className="page narrow"><a href="/" className="back-link"><ArrowRight size={17}/>العودة للرئيسية</a>{success?<div className="success-heading"><span className="success-icon"><CheckCheck size={31}/></span><h1>تم إنشاء طلبك بنجاح</h1><p>احتفظ برقم الطلب لمتابعة حالة العملية.</p></div>:<div className="page-heading"><h1>تفاصيل طلبك</h1><p>كل تفاصيل حوالتك في مكان واحد.</p></div>}
   <div className="form-card order-card"><div className="order-heading"><div><small>رقم الطلب</small><button className="copy-id" onClick={()=>copy(order.id)}><bdi>#{order.id}</bdi><Copy size={15}/></button></div><Status value={order.status}/></div>
   <div className="order-summary"><Detail label="الخدمة" value={order.service_name}/><Detail label="الاتجاه" value={directionName(order.direction)}/><Detail label="المبلغ المطلوب" value={`${money(order.amount)} ${unit(order.currency)}`}/><Detail label="العمولة" value={commissionLabel(order)}/><Detail label="سعر الصرف المستخدم" value={`${money(order.exchange_rate)} ليرة سورية`}/>{order.network&&<Detail label="الشبكة" value={order.network}/>}<Detail label="بيانات الاستلام" value={order.recipient}/><Detail label="تاريخ إنشاء الطلب" value={new Date(order.created_at).toLocaleString('ar-SY')}/></div>
   <div className="order-total"><span>المبلغ الذي سيصل إليك</span><strong>{money(order.final_amount)} <small>{unit(order.final_currency)}</small></strong></div>
   {!success&&['بانتظار الدفع','تم إرسال إثبات الدفع'].includes(order.status)&&<><div className="form-step-label"><span>١</span> تعليمات الدفع</div>{order.service_id==='exchange'&&<Notice>سيتم تحويل المبلغ المطلوب إلى نفس حساب المرسل. يرجى عدم إخفاء اسم المرسل أثناء الإرسال في شام كاش.</Notice>}<p className="muted-text">حوّل المبلغ المطلوب إلى {order.currency==='USDT'?'عنوان USDT التالي على شبكة '+order.network:'حساب شام كاش التالي'}.</p><div className="payment-destination">{showPaymentQr&&<PaymentQr value={order.deposit_address}/>}<div className="payment-destination-info"><small>{order.currency==='USDT'?'عنوان '+order.network:'حساب شام كاش'}</small><div className="payment-address-line"><bdi>{order.deposit_address}</bdi><button type="button" className="icon-copy" onClick={()=>copy(order.deposit_address)} aria-label="نسخ العنوان" title="نسخ"><Copy size={17}/></button></div>{order.currency!=='USDT'&&config.walletOwners?.[order.currency]&&<strong className="wallet-owner">{config.walletOwners[order.currency]}</strong>}</div></div>{order.currency==='USDT'&&<Notice>حوّل عبر شبكة {order.network} فقط. التحويل عبر شبكة مختلفة قد يؤدي إلى فقدان المبلغ.</Notice>}
   <div className="form-step-label"><span>٢</span> إثبات الدفع</div><p className="muted-text">بعد إتمام التحويل، أرسل إثبات الدفع.</p><form onSubmit={send} noValidate><label className="upload-area"><Upload size={24}/><strong>{file?file.name:order.has_proof?'تم إرفاق صورة — اضغط لاستبدالها':'اضغط لرفع صورة إثبات الدفع'}</strong><small>صورة بحد أقصى ٥ ميغابايت</small><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files[0];if(f?.size>5*1024*1024){setError('حجم الصورة يجب ألا يتجاوز 5 ميغابايت.');return;}setFile(f);setError('');}}/></label><div className="or-divider">أو</div><Field label="رقم التحويل TXID"><input dir="ltr" value={txid} onChange={e=>setTxid(e.target.value)} placeholder="أدخل رقم التحويل"/></Field>{error&&<Notice error>{error}</Notice>}<Button className="full" busy={busy} disabled={!file&&!txid&&!order.has_proof}>إرسال إثبات الدفع<ArrowLeft size={17}/></Button></form></>}
   {success&&<div className="submitted-proof"><CheckCircle2 size={22}/><div><strong>تم استلام إيصال الدفع</strong><small>تم إرسال الطلب والإيصال إلى الإدارة للمراجعة.</small></div></div>}
   {order.service_note&&<Notice>{order.service_note}</Notice>}<Button variant="outline" className="full" onClick={()=>{setSuccess(false);load();notify('تم تحديث حالة الطلب');}}><RefreshCw size={16}/>{success?'تتبع الطلب':'تحديث حالة الطلب'}</Button>{success&&<a className="text-center-link" href="/">العودة للرئيسية</a>}</div><MiniSupport/></div>
}
function Detail({label,value}){return <div className="detail"><span>{label}</span><strong>{value||'—'}</strong></div>}
function Help({settings}){const whatsappNumber=String(settings.support_phone||'').replace(/\D/g,'');const whatsappLink=whatsappNumber?'https://wa.me/'+whatsappNumber:'';return <div className="page narrow"><PageHeading title="نحن هنا لمساعدتك" subtitle="استفسار صغير أو مساعدة في طلبك، يسعدنا تواصلك."/><div className="form-card help-card"><Icon className="teal"><Headphones size={32}/></Icon><h2>فريق المارديني، إلى جانبك</h2><p>{settings.contact||'يمكنك متابعة حالة معاملتك مباشرة من صفحة تتبع الطلب.'}</p>{settings.support_phone&&<a className="phone-link" dir="ltr" href={'tel:'+settings.support_phone}>{settings.support_phone}</a>}{whatsappLink&&<a className="button full" href={whatsappLink} target="_blank" rel="noreferrer">تواصل عبر واتساب<ArrowUpLeft size={18}/></a>}<a className="button outline full" href="/track"><Search size={18}/>تتبع طلبك</a><Notice>عند التواصل بخصوص معاملة، جهّز رقم طلبك لنتمكن من مساعدتك بشكل أسرع.</Notice></div></div>}

function Admin({config:publicConfig,refresh,notify}){
 const [config,setConfig]=useState(null),[loading,setLoading]=useState(true),[tab,setTab]=useState('overview'),[orders,setOrders]=useState([]),[stats,setStats]=useState({}),[selected,setSelected]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('');
 const tabs=[['overview','الرئيسية',LayoutDashboard],['orders','الطلبات',ReceiptText],['services','الخدمات',Layers],['tiers','عمولات USDT',Percent],['rate','أسعار الصرف',Banknote],['networks','وسائل الدفع',Network],['settings','الإعدادات',Settings]];
 async function load(){try{const c=await api('/admin/config');setConfig(c);const [o,s]=await Promise.all([api('/admin/orders'),api('/admin/stats')]);setOrders(o);setStats(s);}catch(e){if(e.status===401){setConfig(null);setError('انتهت جلسة الإدارة. يرجى تسجيل الدخول مجددًا.');}else setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 async function save(url,body,method='PUT'){setError('');setMessage('');setBusy(true);try{await api('/admin/'+url,{method,body});await load();await refresh();setMessage('تم حفظ التغييرات بنجاح.');return true;}catch(e){if(e.status===401){setConfig(null);setError('انتهت جلسة الإدارة. يرجى تسجيل الدخول مجددًا ثم إعادة الحفظ.');}else setError(e.message);return false;}finally{setBusy(false);}}
 if(loading)return <div className="loading-screen"><LoaderCircle className="spin"/></div>;
 if(!config)return <Login settings={publicConfig.settings} onLogin={load}/>;
 return <div className="admin-layout"><aside className="admin-sidebar"><Brand settings={config.settings}/><span className="admin-label">لوحة الإدارة</span><nav>{tabs.map(([key,title,I])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setSelected(null);setError('');setMessage('');}}><I size={20}/>{title}</button>)}</nav><a href="/" className="admin-site-link"><ExternalLink size={17}/>عرض المنصة</a><button className="logout" onClick={async()=>{await api('/admin/logout',{method:'POST'});setConfig(null);}}><LogOut size={18}/>تسجيل الخروج</button></aside><main className="admin-main"><div className="admin-top"><div><span className="section-kicker">إدارة المارديني</span><h1>{tabs.find(t=>t[0]===tab)[1]}</h1></div><span className="admin-secure"><ShieldCheck size={17}/>جلسة إدارة محمية</span></div>{error&&<Notice error>{error}</Notice>}{message&&<div className="saved-notice" role="status"><CheckCircle2 size={18}/>{message}</div>}
 {tab==='overview'&&<><div className="stats-grid">{[['طلبات اليوم',stats.today,ReceiptText],['قيد المراجعة',stats.review,Search],['قيد التنفيذ',stats.progress,Clock3],['مكتملة',stats.completed,CheckCircle2]].map(([label,n,I])=><div className="stat-card" key={label}><Icon className="teal"><I size={22}/></Icon><span>{label}</span><strong>{money(n)}</strong></div>)}</div>{(!config.networks.some(n=>n.active)||config.wallets.some(w=>!w.address))&&<Notice>أكمل حسابات شام كاش وعناوين USDT وفعّل الشبكات المطلوبة من قسم «وسائل الدفع» لاستقبال الطلبات.</Notice>}<div className="admin-section-title"><h2>أحدث الطلبات</h2><button onClick={()=>setTab('orders')}>عرض جميع الطلبات<ArrowLeft size={16}/></button></div><OrderList orders={orders.slice(0,6)} open={o=>{setSelected(o);setTab('orders');}}/></>}
 {tab==='orders'&&(selected?<AdminOrder key={selected.id} order={selected} busy={busy} onBack={()=>setSelected(null)} onSave={async b=>{if(await save('orders/'+selected.id,b,'PATCH'))setSelected({...selected,...b});}}/>:<><div className="admin-filters"><input placeholder="البحث برقم الطلب" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">جميع الحالات</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><OrderList orders={orders.filter(o=>o.id.toLowerCase().includes(search.replace('#','').toLowerCase())&&(!filter||o.status===filter))} open={setSelected}/><p className="muted-text">تُعرض أحدث ٥٠٠ عملية.</p></>)}
 {tab==='services'&&<div className="admin-form-grid">{config.services.map(s=><ServiceEditor key={s.id} service={s} busy={busy} save={b=>save('services/'+s.id,b)}/>)}</div>}
 {tab==='rate'&&<RateEditor rates={config.rates} save={b=>save('rate',b)} busy={busy}/>}
 {tab==='tiers'&&<><Notice>عمولة بيع USDT تُدار بشرائح ثابتة غير متداخلة. شراء USDT يعتمد على رسم الشبكة المحدد لكل شبكة أدناه.</Notice><div className="admin-form-grid">{config.tiers.filter(t=>t.direction==='sell').map(t=><TierEditor key={t.id} tier={t} busy={busy} save={b=>save('tiers/'+t.id,b)} remove={()=>save('tiers/'+t.id,undefined,'DELETE')}/>)}<TierEditor key={'new'+config.tiers.length} busy={busy} save={b=>save('tiers',b,'POST')}/></div></>}
 {tab==='networks'&&<><Notice>من هنا تحدد بيانات الدفع التي تظهر للعميل. زر النسخ يظهر دائمًا، ويمكنك تشغيل أو إيقاف QR لكل حساب أو شبكة بشكل مستقل.</Notice><h2 className="admin-subtitle">حسابات شام كاش للإيداع</h2><div className="admin-form-grid">{['USD','SYP'].map(currency=>{const w=config.wallets.find(x=>x.currency===currency);return <WalletEditor key={currency} wallet={w||{currency,address:'',owner_name:'',qr_enabled:true}} busy={busy} save={b=>save(w?'wallets/'+w.id:'wallets',b,w?'PUT':'POST')}/>})}</div><h2 className="admin-subtitle">شبكات وعناوين USDT للإيداع</h2><div className="admin-form-grid">{config.networks.map(n=><NetworkEditor key={n.id} network={n} busy={busy} save={b=>save('networks/'+n.id,b)} remove={()=>save('networks/'+n.id,undefined,'DELETE')}/>)}<NetworkEditor key={'new'+config.networks.length} busy={busy} save={b=>save('networks',b,'POST')}/></div></>}
 {tab==='settings'&&<SettingsEditor settings={config.settings} busy={busy} save={b=>save('settings',b)}/>}
 </main></div>;
}
function Login({settings,onLogin}){const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="login-page"><Brand settings={settings}/><form className="form-card" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/admin/login',{method:'POST',body:{username,password}});await onLogin();}catch(e){setError(e.message);}finally{setBusy(false);}}}><Icon className="teal"><LockKeyhole size={25}/></Icon><h1>مرحبًا بعودتك</h1><p>تسجيل الدخول إلى لوحة الإدارة</p><Field label="اسم المستخدم"><input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/></Field><Field label="كلمة المرور"><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></Field>{error&&<Notice error>{error}</Notice>}<Button className="full" busy={busy}>تسجيل الدخول<ArrowLeft size={17}/></Button></form><a className="back-link" href="/">العودة إلى المنصة<ArrowLeft size={15}/></a></div>}
function OrderList({orders,open}){return <div className="order-list">{orders.length?orders.map(o=><button key={o.id} onClick={()=>open(o)} className="order-list-row"><Icon className={o.service_id==='usdt'?'teal':'gold'}>{o.service_id==='usdt'?<span className="tether-letter">₮</span>:<ArrowDownUp size={20}/>}</Icon><div><strong>{o.service_name}</strong><small><bdi>#{o.id}</bdi></small><small>{directionName(o.direction)} · {new Date(o.created_at).toLocaleDateString('ar-SY')}</small></div><span className="order-list-amount">{money(o.amount)} {unit(o.currency)}</span><Status value={o.status}/><ChevronLeft size={18}/></button>):<div className="empty-state"><ReceiptText size={35}/><h3>لا توجد طلبات لعرضها</h3><p>ستظهر الطلبات الجديدة هنا بمجرد إنشائها.</p></div>}</div>}
function AdminOrder({order,onSave,onBack,busy}){const [status,setStatus]=useState(order.status),[note,setNote]=useState(order.internal_note);return <><button className="back-link" onClick={onBack}><ArrowRight size={16}/>قائمة الطلبات</button><div className="form-card admin-order"><h2><bdi>#{order.id}</bdi></h2>
 <div className="order-summary">{[['الخدمة',order.service_name],['الاتجاه',directionName(order.direction)],['المبلغ',money(order.amount)+' '+unit(order.currency)],['العمولة',commissionLabel(order)],['سعر الصرف',money(order.exchange_rate)],['المبلغ النهائي',money(order.final_amount)+' '+unit(order.final_currency)],['الشبكة',order.network],['عنوان الإيداع',order.deposit_address],['بيانات الاستلام',order.recipient],['TXID',order.txid],['تاريخ الإنشاء',new Date(order.created_at).toLocaleString('ar-SY')],['آخر تحديث',new Date(order.updated_at).toLocaleString('ar-SY')]].map(([label,value])=><Detail key={label} label={label} value={value}/>)}</div>
 {order.proof?<a target="_blank" href={'/api/admin/proofs/'+order.proof}><img className="proof-image" src={'/api/admin/proofs/'+order.proof} alt="إثبات الدفع"/></a>:<Notice>لم يتم إرفاق صورة إثبات دفع.</Notice>}<form onSubmit={e=>{e.preventDefault();onSave({status,internal_note:note});}}><Field label="حالة الطلب"><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="ملاحظة داخلية" hint="تظهر للإدارة فقط ولا يراها المستخدم."><textarea value={note} onChange={e=>setNote(e.target.value)}/></Field><Button busy={busy}>حفظ التغييرات</Button></form></div></>}
function useEditor(initial){const [form,setForm]=useState(initial);return [form,(key,value)=>setForm(f=>({...f,[key]:value}))];}
function EditInput({label,name,form,set,type='text',hint}){return <Field label={label} hint={hint}><input type={type} value={form[name]??''} onChange={e=>set(name,e.target.value)} step={type==='number'?'any':undefined}/></Field>}
function Toggle({checked,onChange,label='مفعلة'}){return <label className="toggle-label"><input type="checkbox" checked={!!checked} onChange={e=>onChange(e.target.checked)}/><span className="toggle-track"/>{label}</label>}
function Editor({title,onSubmit,children,busy,remove,add=false}){const [confirm,setConfirm]=useState(false);return <form className="form-card editor" onSubmit={e=>{e.preventDefault();onSubmit();}}><h3>{title}</h3>{children}<div className="editor-actions"><Button busy={busy}>{add?<Plus size={16}/>:<Check size={16}/>} {add?'إضافة':'حفظ التغييرات'}</Button>{remove&&<button type="button" className="delete-button" onClick={()=>setConfirm(!confirm)}>حذف</button>}</div>{confirm&&<div className="delete-confirm"><span>هل تريد الحذف؟</span><button type="button" onClick={remove}>تأكيد الحذف</button><button type="button" onClick={()=>setConfirm(false)}>تراجع</button></div>}</form>}
function ServiceEditor({service,save,busy}){const [f,set]=useEditor(service),[iconV,setIconV]=useState(Date.now()),[iconBusy,setIconBusy]=useState(false),[iconError,setIconError]=useState('');const toggleList=(key,value)=>set(key,f[key].includes(value)?f[key].filter(x=>x!==value):[...f[key],value]);async function uploadIcon(file){if(!file)return;setIconBusy(true);setIconError('');try{const data=new FormData();data.append('icon',file);await api('/service-icon/'+service.id,{method:'POST',body:data});setIconV(Date.now());}catch(e){setIconError(e.message);}finally{setIconBusy(false);}}return <Editor title={service.name} onSubmit={()=>save(f)} busy={busy}><Field label="أيقونة الخدمة" hint="PNG أو JPG أو WEBP أو SVG — حتى 2MB"><div className="service-icon-admin"><img src={'/api/service-icon/'+service.id+'?v='+iconV} alt="معاينة الأيقونة"/><label className="service-icon-upload">{iconBusy?'جارٍ الرفع...':'رفع / تغيير الأيقونة'}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" disabled={iconBusy} onChange={e=>uploadIcon(e.target.files?.[0])}/></label></div>{iconError&&<Notice error>{iconError}</Notice>}</Field><EditInput label="اسم الخدمة" name="name" form={f} set={set}/><EditInput label="الوصف" name="description" form={f} set={set}/><div className="form-grid"><EditInput label={'الحد الأدنى ('+(service.id==='usdt'?'USDT':'دولار')+')'} name="minimum" type="number" form={f} set={set}/><EditInput label="الحد الأقصى (اختياري)" name="maximum" type="number" form={f} set={set}/></div><Field label="ملاحظة الخدمة"><textarea value={f.note} onChange={e=>set('note',e.target.value)}/></Field><Field label="الاتجاهات المتاحة"><div className="checkbox-options">{(service.id==='usdt'?['sell','buy']:['usd-syp','syp-usd']).map(d=><label key={d}><input type="checkbox" checked={f.directions.includes(d)} onChange={()=>toggleList('directions',d)}/>{directionName(d)}</label>)}</div></Field><Field label="العملات المتاحة"><div className="checkbox-options">{['USD','SYP'].map(c=><label key={c}><input type="checkbox" checked={f.currencies.includes(c)} onChange={()=>toggleList('currencies',c)}/>{unit(c)}</label>)}</div></Field><Toggle checked={f.active} onChange={v=>set('active',v)} label="الخدمة مفعلة"/></Editor>}
function TierEditor({tier,save,remove,busy}){const [f,set]=useEditor({minimum:'',maximum:'',fixed_amount:'',percent:'',type:'fixed',active:true,direction:'sell',...tier});const percent=f.type==='percent';return <Editor title={tier?'شريحة بيع USDT':'إضافة شريحة بيع'} onSubmit={()=>save({...f,direction:'sell',type:percent?'percent':'fixed',fixed_amount:percent?0:f.fixed_amount,percent:percent?f.percent:0})} busy={busy} remove={remove} add={!tier}><div className="form-grid"><EditInput label="من مبلغ (USDT)" name="minimum" type="number" form={f} set={set}/><EditInput label="إلى مبلغ (USDT)" name="maximum" type="number" form={f} set={set}/></div><Field label="نوع العمولة"><select value={f.type||'fixed'} onChange={e=>set('type',e.target.value)}><option value="fixed">مبلغ ثابت</option><option value="percent">نسبة مئوية %</option></select></Field>{percent?<EditInput label="نسبة العمولة (%)" name="percent" type="number" form={f} set={set} hint="مثال: 0.01 تعني 0.01% من مبلغ العملية. يمكنك إدخال كسور دقيقة مثل 0.005."/>:<EditInput label="العمولة الثابتة (دولار)" name="fixed_amount" type="number" form={f} set={set} hint="مثال: 1–100 عمولتها 1 دولار، والشريحة التالية تبدأ من 101."/>}<Toggle checked={f.active} onChange={v=>set('active',v)} label="الشريحة مفعلة"/></Editor>}
function NetworkEditor({network,save,remove,busy}){const [f,set]=useEditor(network||{name:'',address:'',buy_fee:0,active:false,qr_enabled:true});return <Editor title={network?network.name:'إضافة شبكة USDT'} onSubmit={()=>save(f)} busy={busy} remove={remove} add={!network}><EditInput label="اسم الشبكة" name="name" form={f} set={set} hint="مثال: TRC20 أو BEP20"/><EditInput label="عنوان USDT للإيداع" name="address" form={f} set={set} hint="هذا هو عنوان محفظتك الذي سيظهر للعميل عند تحويل USDT إليك."/><EditInput label="رسوم شراء USDT عبر هذه الشبكة ($)" name="buy_fee" type="number" form={f} set={set} hint="تُخصم من المبلغ الذي أدخله العميل. مثال: 100$ ورسوم 2$ = 98 USDT."/><Toggle checked={f.qr_enabled!==false} onChange={v=>set('qr_enabled',v)} label="إظهار QR للعميل"/><Toggle checked={f.active} onChange={v=>set('active',v)} label="الشبكة مفعلة"/></Editor>}
function WalletEditor({wallet,save,busy}){const [f,set]=useEditor({...wallet,qr_enabled:wallet.qr_enabled!==false});return <Editor title={'شام كاش · '+unit(wallet.currency)} onSubmit={()=>save(f)} busy={busy}><EditInput label="رقم / حساب شام كاش للإيداع" name="address" form={f} set={set} hint="هذا الحساب سيظهر للعميل مع زر النسخ عند الدفع لك عبر شام كاش."/><EditInput label="اسم صاحب الحساب" name="owner_name" form={f} set={set} hint="يظهر للعميل لتأكيد الحساب قبل التحويل."/><Toggle checked={f.qr_enabled!==false} onChange={v=>set('qr_enabled',v)} label="إظهار QR للعميل"/></Editor>}
function RateEditor({rates,save,busy}){const [f,set]=useEditor({buyUsd:rates?.buyUsd||'',sellUsd:rates?.sellUsd||''});return <div className="rate-editor"><Editor title="أسعار شراء وبيع الدولار" onSubmit={()=>save(f)} busy={busy}><EditInput label="سعر شراء الدولار من العميل (SYP لكل 1 USD)" name="sellUsd" type="number" form={f} set={set} hint="إذا كان العميل معه دولار ويريد ليرة سورية، فهذا هو المبلغ الذي يقبضه عن كل 1 دولار. مثال: 136."/><EditInput label="سعر بيع الدولار للعميل (SYP لكل 1 USD)" name="buyUsd" type="number" form={f} set={set} hint="إذا كان العميل معه ليرة سورية ويريد دولار، فهذا هو المبلغ الذي يدفعه عن كل 1 دولار. مثال: 138. ويُستخدم أيضًا عند شراء USDT والدفع بالليرة."/><Notice>السعران مستقلان تمامًا: دولار → ليرة يستخدم سعر شراء الدولار من العميل، وليرة → دولار يستخدم سعر بيع الدولار للعميل. لا يتم اشتقاق أحد السعرين من الآخر.</Notice></Editor></div>}
function SettingsEditor({settings,save,busy}){const [f,set]=useEditor(settings);return <div className="settings-editor"><Editor title="إعدادات المنصة" onSubmit={()=>save(f)} busy={busy}><EditInput label="اسم المنصة" name="name" form={f} set={set}/><EditInput label="رابط الشعار" name="logo" form={f} set={set} hint="رابط آمن أو مسار ملف مثل /logo.png"/>{f.logo&&<img className="logo-preview" src={f.logo} alt="معاينة الشعار"/>}<EditInput label="بيانات التواصل" name="contact" form={f} set={set}/><div className="form-grid"><EditInput label="رقم الدعم" name="support_phone" form={f} set={set}/><EditInput label="رابط الدعم" name="support_link" form={f} set={set}/></div><Field label="رسالة عامة للمستخدمين"><textarea value={f.announcement} onChange={e=>set('announcement',e.target.value)}/></Field><Toggle checked={f.active} onChange={v=>set('active',v)} label="المنصة مفعلة"/></Editor></div>}

createRoot(document.getElementById('root')).render(<App/>);
if('serviceWorker' in navigator&&import.meta.env.PROD)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
